import { useVehicleStore } from '@/state/vehicleStore'
import { MechanicalOdometer } from '../gauges/classic/ClassicGauges'
import { NavArrow } from '../GpsScreen'
import './navigation.css'
export function CompassRose({ heading, valid = true }: { heading: number; valid?: boolean }) {
  return <svg viewBox="0 0 340 340" className="rd-compass" role="img" aria-label={valid?`Bearing ${Math.round(heading)} degrees`:'Position unavailable'}><circle cx="170" cy="170" r="164" fill="#111b15" stroke="#b3b69f" strokeWidth="4"/><circle cx="170" cy="170" r="155" fill="none" stroke="#48513f"/><g transform={`rotate(${-heading} 170 170)`}>{Array.from({length:72},(_,i)=><line key={i} x1="170" y1="23" x2="170" y2={i%9===0?43:30} transform={`rotate(${i*5} 170 170)`} stroke="var(--cl-primary)"/>)}{['N','E','S','W'].map((n,i)=><text key={n} x="170" y="67" textAnchor="middle" transform={`rotate(${i*90} 170 170)`} fill="var(--cl-primary-bright)" fontSize="25">{n}</text>)}<path d="M170 83 L187 153 L257 170 L187 187 L170 257 L153 187 L83 170 L153 153 Z" fill="#b8bba3" opacity=".3"/></g><path d="M170 78 L186 178 L170 166 L154 178 Z" fill={valid?'#d2b77d':'#565b4c'}/><circle cx="170" cy="170" r="6" fill="#e6d8b8"/><text x="170" y="225" textAnchor="middle" fill="var(--cl-primary-bright)" fontSize="21">{valid?`${Math.round(heading)}°`:'NO FIX'}</text></svg>
}
export function ClassicNavigation() {
  const t=useVehicleStore(s=>s.telemetry), connections=useVehicleStore(s=>s.connections), parked=useVehicleStore(s=>s.parkedLocation), mode=useVehicleStore(s=>s.navMode), nav=useVehicleStore(s=>s.navInstruction), setMode=useVehicleStore(s=>s.setNavMode)
  const fix=connections.gps==='FIX', phone=connections.phone==='CONNECTED'
  return <div className="rd-rally-nav"><header><span>RETRODRIVE</span><h1>Rally & Touring Instruments</h1><span>POSITION / TRIP</span></header><div className="rd-rally-body"><CompassRose heading={t.headingDeg.value} valid={fix}/><div className="rd-rally-trip"><small>TRIP RECORDER / km</small><b>{t.tripDistanceKm.value.toFixed(1)}</b><svg viewBox="80 195 140 55" width="210" height="80"><MechanicalOdometer value={t.odometerKm.value}/></svg><dl><dt>Altitude</dt><dd>{fix?t.altitudeM.value.toFixed(0)+' m':'No fix'}</dd><dt>Satellites</dt><dd>{fix?t.satelliteCount.value:0}</dd><dt>Accuracy</dt><dd>{fix?'±'+t.gpsAccuracyM.value.toFixed(1)+' m':'Unavailable'}</dd></dl></div><div className="rd-rally-directions">{mode==='PHONE_ASSISTED'&&nav&&phone?<><NavArrow kind={nav.kind}/><h2>{nav.kind.replaceAll('_',' ')}</h2><strong>{nav.distanceM} m</strong><p>{nav.destinationDistanceKm?.toFixed(1)??'—'} km remaining · {nav.destinationEtaMin??'—'} min</p></>:<><small>{mode==='PHONE_ASSISTED'&&!phone?'PHONE DISCONNECTED':'STANDALONE POSITION'}</small><h2>{fix?'Position acquired':'Searching for position'}</h2><p>{t.latitude.value.toFixed(5)}°<br/>{t.longitude.value.toFixed(5)}°</p></>}<hr/><small>LAST PARKED</small><p>{parked?`${parked.lat.toFixed(5)}°, ${parked.lon.toFixed(5)}°`:'No parked position recorded'}</p></div></div><footer><button onClick={()=>setMode('STANDALONE')}>COMPASS</button><button onClick={()=>setMode('PHONE_ASSISTED')}>PHONE GUIDANCE</button><span>{fix?'POSITION RECEIVER ONLINE':'POSITION RECEIVER · '+connections.gps}</span></footer></div>
}
